# TCL File Generated by Component Editor 23.1
# Fri Oct 11 11:01:26 MDT 2024
# DO NOT MODIFY


# 
# led_patters_avalon "led_patters_avalon" v1.0
# Jonny Hughes 2024.10.11.11:01:26
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module led_patters_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME led_patters_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Jonny Hughes"
set_module_property DISPLAY_NAME led_patters_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_patterns_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_patterns_avalon.vhd VHDL PATH ../hdl/LED_patterns/led_patterns_avalon.vhd TOP_LEVEL_FILE
add_fileset_file clk_gen.vhd VHDL PATH ../hdl/LED_patterns/clk_gen.vhd
add_fileset_file led_patterns.vhd VHDL PATH ../hdl/LED_patterns/led_patterns.vhd
add_fileset_file led7_base.vhd VHDL PATH ../hdl/LED_patterns/pattern_components/led7/led7_base.vhd
add_fileset_file state0.vhd VHDL PATH ../hdl/LED_patterns/pattern_components/state0/state0.vhd
add_fileset_file state1.vhd VHDL PATH ../hdl/LED_patterns/pattern_components/state1/state1.vhd
add_fileset_file state2.vhd VHDL PATH ../hdl/LED_patterns/pattern_components/state2/state2.vhd
add_fileset_file state3.vhd VHDL PATH ../hdl/LED_patterns/pattern_components/state3/state3.vhd
add_fileset_file state4.vhd VHDL PATH ../hdl/LED_patterns/pattern_components/state4/state4.vhd
add_fileset_file async_conditioner.vhd VHDL PATH ../hdl/async-conditioner/async_conditioner.vhd
add_fileset_file debouncer.vhd VHDL PATH ../hdl/debouncer/debouncer.vhd
add_fileset_file one_pulse.vhd VHDL PATH ../hdl/one_pulse/one_pulse.vhd
add_fileset_file synchronizer.vhd VHDL PATH ../hdl/synchronizer/synchronizer.vhd
add_fileset_file timed-counter.vhd VHDL PATH ../hdl/timed_counter/timed-counter.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0_1_1
# 
add_interface avalon_slave_0_1_1 avalon end
set_interface_property avalon_slave_0_1_1 addressUnits WORDS
set_interface_property avalon_slave_0_1_1 associatedClock clock
set_interface_property avalon_slave_0_1_1 associatedReset rst_1_1
set_interface_property avalon_slave_0_1_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1_1 holdTime 0
set_interface_property avalon_slave_0_1_1 linewrapBursts false
set_interface_property avalon_slave_0_1_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1_1 readLatency 0
set_interface_property avalon_slave_0_1_1 readWaitTime 1
set_interface_property avalon_slave_0_1_1 setupTime 0
set_interface_property avalon_slave_0_1_1 timingUnits Cycles
set_interface_property avalon_slave_0_1_1 writeWaitTime 0
set_interface_property avalon_slave_0_1_1 ENABLED true
set_interface_property avalon_slave_0_1_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1_1 avs_read read Input 1
add_interface_port avalon_slave_0_1_1 avs_write write Input 1
add_interface_port avalon_slave_0_1_1 avs_address address Input 2
add_interface_port avalon_slave_0_1_1 avs_readdata readdata Output 32
add_interface_port avalon_slave_0_1_1 avs_writedata writedata Input 32
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point export_1
# 
add_interface export_1 conduit end
set_interface_property export_1 associatedClock ""
set_interface_property export_1 associatedReset ""
set_interface_property export_1 ENABLED true
set_interface_property export_1 EXPORT_OF ""
set_interface_property export_1 PORT_NAME_MAP ""
set_interface_property export_1 CMSIS_SVD_VARIABLES ""
set_interface_property export_1 SVD_ADDRESS_GROUP ""

add_interface_port export_1 led led Output 8
add_interface_port export_1 push_button push_button Input 1
add_interface_port export_1 switches switches Input 4


# 
# connection point rst_1_1
# 
add_interface rst_1_1 reset end
set_interface_property rst_1_1 associatedClock clock
set_interface_property rst_1_1 synchronousEdges DEASSERT
set_interface_property rst_1_1 ENABLED true
set_interface_property rst_1_1 EXPORT_OF ""
set_interface_property rst_1_1 PORT_NAME_MAP ""
set_interface_property rst_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property rst_1_1 SVD_ADDRESS_GROUP ""

add_interface_port rst_1_1 rst reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

